tunnel: signauthentics-tunnel
credentials-file: /etc/cloudflared/credentials.json

ingress:
  - hostname: app.minhmice.com
    service: http://web:3000
  - hostname: backend.minhmice.com
    service: http://web:3000
  - hostname: img.minhmice.com
    service: http://imgproxy:8080
  - service: http_status:404